# The PublicBodyCategories structure works like this:
# [
#   "Main category name",
#       [ "tag_to_use_as_category", "Sub category title", "sentence that can describes things in this subcategory" ],
#       [ "another_tag", "Second sub category title", "another descriptive sentence for things in this subcategory"],
#   "Another main category name",
#       [ "another_tag_2", "Another sub category title", "another descriptive sentence"]
# ])

PublicBodyCategories.add(:en, [
   "Republički organi",
[ "najviši_republički_organi", "Najviši republički organi", "Najviši republički organi"],
["samostalni_republički_organi_i_nezavisna_tela", "Samostalni republički organi i nezavisna tela", "Samostalni republički organi i nezavisna tela"],
["ministarstva", "Ministarstva", "Ministarstva"],
["republičke_agencije,_zavodi_i_druge_organizacije", "Republičke agencije, zavodi i druge organizacije", "Republičke agencije, zavodi i druge organizacije"],
"Upravni okruzi",
["upravni_okruzi", "Upravni okruzi", "Upravni okruzi"],
"Pravosudni organi",
["privredni_sudovi", "Privredni sudovi", "Privredni sudovi"],
["upravn_sudovi", "Upravn sudovi", "Upravn sudovi"],
["apelacioni_sudovi_opšte_nadležnosti", "Apelacioni sudovi opšte nadležnosti", "Apelacioni sudovi opšte nadležnosti"],
["viši_sudovi_opšte_nadležnosti", "Viši sudovi opšte nadležnosti", "Viši sudovi opšte nadležnosti"],
["osnovni_sudovi", "Osnovni sudovi", "Osnovni sudovi"],
["prekršajni_sudovi", "Prekršajni sudovi", "Prekršajni sudovi"],
["javna_tužilaštva", "Javna tužilaštva", "Javna tužilaštva"],
"Pokrajinski i lokalni organi vlasti",
["organi_i_organizacije_ap_vojvodine", "Organi i organizacije AP Vojvodine", "Organi i organizacije AP Vojvodine"],
["javna_preduzeća,_ustanove_i_druge_javne_službe_ap_vojvodine", "Javna preduzeća, ustanove i druge javne službe AP Vojvodine", "Javna preduzeća, ustanove i druge javne službe AP Vojvodine"],
"Javna preduzeća i druga pravna lica sa većinskim državnim kapitalom ili javnim ovlašćenjima",
["javna_preduzeća_i_druga_pravna_lica_sa_većinskim_državnim_kapitalom_ili_javnim_ovlašćenjima", "Javna preduzeća i druga pravna lica sa većinskim državnim kapitalom ili javnim ovlašćenjima", "Javna preduzeća i druga pravna lica sa većinskim državnim kapitalom ili javnim ovlašćenjima"],
"Ustanove i druge javne službe",
["ustanove_obrazovanja", "Ustanove obrazovanja", "Ustanove obrazovanja"],
["ustanove_i_druge_javne_službe_socijalne_zaštite", "Ustanove i druge javne službe socijalne zaštite", "Ustanove i druge javne službe socijalne zaštite"],
["ustanove_i_druge_javne_službe_u_oblasti_zdravlja_ljudi", "Ustanove i druge javne službe u oblasti zdravlja ljudi", "Ustanove i druge javne službe u oblasti zdravlja ljudi"],
["ustanove_u_oblasti_pravosuđa", "Ustanove u oblasti pravosuđa", "Ustanove u oblasti pravosuđa"],
["ustanove_u_oblasti_privrede,_poljoprivrede,_šumarstva_i_vodoprivrede", "Ustanove u oblasti privrede, poljoprivrede, šumarstva i vodoprivrede", "Ustanove u oblasti privrede, poljoprivrede, šumarstva i vodoprivrede"],
["ustanove_u_oblasti_odbrane", "Ustanove u oblasti odbrane", "Ustanove u oblasti odbrane"],
"Gradovi i gradske opštine",
["grad_beograd", "Grad Beograd", "Grad Beograd"],
["grad_kragujevca", "Grad Kragujevca", "Grad Kragujevca"],
["grad_niš", "Grad Niš", "Grad Niš"],
["grad_novi_sad", "Grad Novi Sad", "Grad Novi Sad"],
["grad_valjevo", "Grad Valjevo", "Grad Valjevo"],
["grad_vranje", "Grad Vranje", "Grad Vranje"],
["grad_zaječar", "Grad Zaječar", "Grad Zaječar"],
["grad_zrenjanin", "Grad Zrenjanin", "Grad Zrenjanin"],
["grad_jagodina", "Grad Jagodina", "Grad Jagodina"],
["grad_kraljevo", "Grad Kraljevo", "Grad Kraljevo"],
["grad_kruševac", "Grad Kruševac", "Grad Kruševac"],
["grad_leskovac", "Grad Leskovac", "Grad Leskovac"],
["grad_loznica", "Grad Loznica", "Grad Loznica"],
["grad_novi_pazar", "Grad Novi Pazar", "Grad Novi Pazar"],
["grad_pančevo", "Grad Pančevo", "Grad Pančevo"],
["grad_požarevac", "Grad Požarevac", "Grad Požarevac"],
["grad_smederevo", "Grad Smederevo", "Grad Smederevo"],
["grad_sombor", "Grad Sombor", "Grad Sombor"],
["grad_sremska_mitrovica", "Grad Sremska Mitrovica", "Grad Sremska Mitrovica"],
["grad_subotica", "Grad Subotica", "Grad Subotica"],
["grad_užice", "Grad Užice", "Grad Užice"],
["grad_Čačak", "Grad Čačak", "Grad Čačak"],
["grad_Šabac", "Grad Šabac", "Grad Šabac"],
"Opštine u Srbiji",
["severnobački_upravni_okrug", "Severnobački upravni okrug", "Severnobački upravni okrug"],
["srednjobanatski_upravni_okrug", "Srednjobanatski upravni okrug", "Srednjobanatski upravni okrug"],
["severnobanatski_upravni_okrug", "Severnobanatski upravni okrug", "Severnobanatski upravni okrug"],
["južnobanatski_upravni_okrug", "Južnobanatski upravni okrug", "Južnobanatski upravni okrug"],
["zapadnobački_upravni_okrug", "Zapadnobački upravni okrug", "Zapadnobački upravni okrug"],
["južnobački_upravni_okrug", "Južnobački upravni okrug", "Južnobački upravni okrug"],
["sremski_upravni_okrug", "Sremski upravni okrug", "Sremski upravni okrug"],
["mačvanski_upravni_okrug", "Mačvanski upravni okrug", "Mačvanski upravni okrug"],
["kolubarski_upravni_okrug", "Kolubarski upravni okrug", "Kolubarski upravni okrug"],
["podunavski_upravni_okrug", "Podunavski upravni okrug", "Podunavski upravni okrug"],
["braničevski_upravni_okrug", "Braničevski upravni okrug", "Braničevski upravni okrug"],
["Šumadijski_upravni_okrug", "Šumadijski upravni okrug", "Šumadijski upravni okrug"],
["pomoravski_upravni_okrug", "Pomoravski upravni okrug", "Pomoravski upravni okrug"],
["borski_upravni_okrug", "Borski upravni okrug", "Borski upravni okrug"],
["zaječarski_upravni_okrug", "Zaječarski upravni okrug", "Zaječarski upravni okrug"],
["zlatiborski_upravni_okrug", "Zlatiborski upravni okrug", "Zlatiborski upravni okrug"],
["moravički_upravni_okrug", "Moravički upravni okrug", "Moravički upravni okrug"],
["raški_upravni_okrug", "Raški upravni okrug", "Raški upravni okrug"],
["rasinski_upravni_okrug", "Rasinski upravni okrug", "Rasinski upravni okrug"],
["nišavski_upravni_okrug", "Nišavski upravni okrug", "Nišavski upravni okrug"],
["toplički_upravni_okrug", "Toplički upravni okrug", "Toplički upravni okrug"],
["pirotski_upravni_okrug", "Pirotski upravni okrug", "Pirotski upravni okrug"],
["jablanički_upravni_okrug", "Jablanički upravni okrug", "Jablanički upravni okrug"],
["pčinjski_upravni_okrug", "Pčinjski upravni okrug", "Pčinjski upravni okrug"],
])
